CWIDTH ?= 2000
CHEIGHT ?= 800
SHEIGHT ?= 800
SWIDTH ?= 600

diagrams:
	mmdc -i imapcl-class.mmd -o imapcl-class.png --theme forest --width $(CWIDTH) --height $(CHEIGHT)
	mmdc -i imapcl-state.mmd -o imapcl-state.png --theme forest --width $(SWIDTH) --height $(SHEIGHT)
